
@base_url=https://localhost:49329/api/
@base_url_s=https://localhost:49328/api/

###
POST {{base_url_s}}chat/async/user1-con1
Content-Type: application/json

"What was my last question?"
####
"How are you?"
"Turn on the Kitchen Light and show me the result"
"Give me list of lights"

#############
POST {{base_url_s}}chat/streaming/user1-con1
Content-Type: application/json

"How are you today?"
###
"Give me list of lights"
"Hi, there"
"List all my questions so far I have asked, DO NOT add anything else, ONLY my questions"
"What was my last question?"
###


############ 

GET {{base_url_s}}health/sync
Content-Type: application/json

#### 

GET {{base_url_s}}health/stream
Content-Type: application/json