<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.VectorData.Qdrant" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
        <PackageReference Include="Microsoft.SemanticKernel" />
        <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="VectoreStores\AzureAISearchVectorStore\" />
      <Folder Include="VectoreStores\RedisVectorStore\" />
    </ItemGroup>

</Project>
